export function returnInputTransportConfiguration() {
  return {
    number: {
      element: "input",
      type: "number",
      value: "",
      validation: { required: true },
      valid: false,
      touched: false,
      errorMessage: "",
      label: "Номер:",
    },
    type: {
      element: "input",
      type: "text",
      value: "",
      validation: { required: true, maxLength: 60 },
      valid: false,
      touched: false,
      errorMessage: "",
      label: "Тип:",
    },
    capacity: {
      element: "input",
      type: "number",
      value: "",
      validation: { required: true },
      valid: false,
      touched: false,
      errorMessage: "",
      label: "Вместимость:",
    },
    weight: {
      element: "input",
      type: "number",
      value: "",
      validation: { required: true },
      valid: false,
      touched: false,
      errorMessage: "",
      label: "Вес:",
    },
    speed: {
      element: "input",
      type: "number",
      value: "",
      validation: { required: true },
      valid: false,
      touched: false,
      errorMessage: "",
      label: "Скорость:",
    },
    technicalСondition: {
      element: "input",
      type: "number",
      value: "",
      validation: { required: true },
      valid: false,
      touched: false,
      errorMessage: "",
      label: "Техническое состояние:",
    },
  };
}
